permalink: /:year/:month/:day/:title.md
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

markdown: kramdown

title : e2mc's blog
author :
  name : e2mc
  email : e2mc01@163.com
  github : e2mc 


production_url : http://linusp.github.io

nav:
  - text: 分类
    url : /categories.md 
  - text: 存档
    url : /archive.md
  - text: 关于
    url : /about.md

JB :
  version : 0.3.0

  archive_path: /archive.md
  categories_path : /categories.md
  tags_path : /tags.md